### ISSUE TITLE
tf.hub to ONNX conversion 

### ISSUE THREAD

**Issue by BaMarcy** [kaiidams/YamNetUnityDemo#8]
Hi, nice work first of all!

Secondly, could you help me how to convert a tf model from the tf.hub to an ONNX? I am getting errors unfortunately... I would like to do sth similar but with trillsson.

https://tfhub.dev/google/trillsson5/1  

Thanks :)

**Comment by kaiidams** [comment]
Hi BaMarcy

Converting with tf2onnx.

```sh
python -m tf2onnx.convert --saved-model ./model --output a.onnx
```

This makes error as below. Probably it does unusual way to use `tf.gather` (maybe for embedding lookup). If you have source code, you can investigate it. You may try Hugging Face. It has better support of ONNX, it this one is the same as your model  https://github.com/huggingface/transformers/pull/17387

```
ValueError: make_sure failure: Axis of GatherV2 node must be constant                                          [22/1963]2023-10-22 10:05:24,425 - ERROR - Unsupported ops: Counter({'Rank': 3})                                                 Traceback (most recent call last):                                                                                        File "/home/kaiida/anaconda3/envs/py310-tf2/lib/python3.10/runpy.py", line 196, in _run_module_as_main                    return _run_code(code, main_globals, None,
  File "/home/kaiida/anaconda3/envs/py310-tf2/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/kaiida/anaconda3/envs/py310-tf2/lib/python3.10/site-packages/tf2onnx/convert.py", line 714, in <module>
    main()
  File "/home/kaiida/anaconda3/envs/py310-tf2/lib/python3.10/site-packages/tf2onnx/convert.py", line 273, in main
    model_proto, _ = _convert_common(
  File "/home/kaiida/anaconda3/envs/py310-tf2/lib/python3.10/site-packages/tf2onnx/convert.py", line 168, in _convert_common
    g = process_tf_graph(tf_graph, const_node_values=const_node_values,
```
